openapi: 3.0.4
info:
  title: SSL Certificate Checker
  description: >-
    SSL Checker is a simple tool for checking SSL certificates. It returns the
    SSL certificate details of a website.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/sslchecker:
    get:
      summary: Check SSL Certificate
      description: Check the SSL certificate of a domain
      operationId: sslchecker
      parameters:
        - name: domain
          in: query
          schema:
            type: string
          required: true
          description: The domain of the website to check the SSL certificate of
          example: ebay.com
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  subject:
                    C: US
                    ST: California
                    O: eBay, Inc.
                    CN: ebay.com
                  issuer:
                    C: GB
                    O: Sectigo Limited
                    CN: Sectigo Public Server Authentication CA OV R36
                  subjectaltname: >-
                    DNS:ebay.com, DNS:befr.ebay.be, DNS:benl.ebay.be,
                    DNS:cafr.ebay.ca, DNS:e-bay.it, DNS:ebay.at, DNS:ebay.be,
                    DNS:ebay.ca, DNS:ebay.ch, DNS:ebay.co.uk, DNS:ebay.com.au,
                    DNS:ebay.com.hk, DNS:ebay.com.my, DNS:ebay.com.sg,
                    DNS:ebay.de, DNS:ebay.es, DNS:ebay.fr, DNS:ebay.ie,
                    DNS:ebay.in, DNS:ebay.it, DNS:ebay.nl, DNS:ebay.ph,
                    DNS:ebay.pl, DNS:ebay.us, DNS:ebay.vn, DNS:wwww.ebay.co.uk,
                    DNS:wwww.ebay.com, DNS:wwww.ebay.com.au, DNS:wwww.ebay.de,
                    DNS:wwww.ebay.in, DNS:wwww.ebay.it
                  infoAccess:
                    CA Issuers - URI:
                      - >-
                        http://crt.sectigo.com/SectigoPublicServerAuthenticationCAOVR36.crt
                    OCSP - URI:
                      - http://ocsp.sectigo.com
                  ca: false
                  bits: 2048
                  valid_from: Jul 28 00:00:00 2025 GMT
                  valid_to: Jul 28 23:59:59 2026 GMT
                  serialNumber: 99F408949A6416EDC3B8F5EC77B2EBE5
                  domain: ebay.com
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
